#!/usr/bin/env python3
"""Emit every timing number the paper states, as macros, from results/timing_a5000.json.

WHY THIS EXISTS. The accuracy tables and the statistics have been script-generated for months, but
the latency numbers -- which carry one of the paper's two main claims -- were typed straight into
main.tex. Nothing in the repository could reproduce them, so nothing could contradict them either,
and three of them turned out to be wrong at once: the fit range had no provenance, the per-image
figure was out by two orders of magnitude because it timed the head at feature resolution while the
model emits a native-resolution mask, and nnU-Net's cost was both the wrong value and wrongly
claimed to be independent of field size. A number no script can regenerate is a number no one
checks.

The ratio is deliberately computed from the LOWER bound on nnU-Net's largest field, which did not
finish inside its cap. That makes the reported speed-up conservative in nnU-Net's favour: the true
ratio is larger. Rounding is toward the less flattering value for the same reason.

  ASG_TIMING=results/timing_a5000.json ASG_SEM_OUT=paper/isbi2027 python scripts/make_timing_numbers.py
"""
import json
import math
import os
import sys

SRC = os.environ.get("ASG_TIMING", "results/timing_a5000.json")
OUT = os.environ.get("ASG_SEM_OUT", "paper/isbi2027")

with open(SRC) as fh:
    d = json.load(fh)

ours = sorted(d["ours"], key=lambda r: r["side_px"])
nn = {r["dataset"]: r for r in d["nnunet"]}
small, large = ours[0], ours[-1]

for r in ours:                      # the file is the record; a hole in it must not become a macro
    for k in ("fit_s", "encode_ms", "image_to_mask_ms", "bank_only_ms"):
        if r.get(k) is None:
            sys.exit(f"REFUSING: {r['dataset']} has no {k}; a missing measurement would silently "
                     f"become a plausible macro")

fit_med_small = round(small["fit_s"]["median"])
fit_med_large = round(large["fit_s"]["median"])
fit_draw_lo = math.floor(min(r["fit_s"]["min"] for r in ours))
fit_draw_hi = math.ceil(max(r["fit_s"]["max"] for r in ours))
enc_lo = round(min(r["encode_ms"] for r in ours))
enc_hi = round(max(r["encode_ms"] for r in ours))
mask_lo = min(r["image_to_mask_ms"] for r in ours) / 1000
mask_hi = max(r["image_to_mask_ms"] for r in ours) / 1000

# Speed-up against nnU-Net at each end of the field range, floored so the claim understates itself.
ratio_lo = math.floor(nn["hrf"]["fit_s"] / large["fit_s"]["median"])
ratio_hi = math.floor(nn["dsb2018"]["fit_s"] / small["fit_s"]["median"])
bank_share = large["bank_only_ms"] / large["image_to_mask_ms"]

lines = [
    "% Generated by scripts/make_timing_numbers.py from results/timing_a5000.json. Do not hand-edit.",
    f"% Measured on one idle {d['device']}, {d['date']}. See registry C66 for conditions.",
    f"\\newcommand{{\\fitSmall}}{{{fit_med_small}}}",
    f"\\newcommand{{\\fitLarge}}{{{fit_med_large}}}",
    f"\\newcommand{{\\fitDrawLo}}{{{fit_draw_lo}}}",
    f"\\newcommand{{\\fitDrawHi}}{{{fit_draw_hi}}}",
    f"\\newcommand{{\\encLo}}{{{enc_lo}}}",
    f"\\newcommand{{\\encHi}}{{{enc_hi}}}",
    f"\\newcommand{{\\maskLo}}{{{mask_lo:.2f}}}",
    f"\\newcommand{{\\maskHi}}{{{mask_hi:.1f}}}",
    f"\\newcommand{{\\encLargeS}}{{{large['encode_ms'] / 1000:.2f}}}",
    f"\\newcommand{{\\nnSmall}}{{{round(nn['dsb2018']['fit_s'] / 10) * 10}}}",
    f"\\newcommand{{\\nnLarge}}{{{round(nn['hrf']['fit_s'])}}}",
    f"\\newcommand{{\\costRatioLo}}{{{ratio_lo}}}",
    f"\\newcommand{{\\costRatioHi}}{{{ratio_hi}}}",
    f"\\newcommand{{\\bankShareOfMask}}{{{bank_share:.2f}}}",
]
path = os.path.join(OUT, "numbers_timing.tex")
with open(path, "w") as fh:
    fh.write("\n".join(lines) + "\n")
print("\n".join(lines))
print(f"\nwrote {path}")
print(f"  nnU-Net at the largest field is a {nn['hrf']['bound']} bound, so {ratio_lo}x is a floor")
